#pragma once

#define __global __attribute__((annotate("cl_global")))
#define __kernel __attribute__((annotate("cl_kernel")))
#define __local  __attribute__((annotate("cl_local" )))

typedef unsigned char uchar;
typedef unsigned short ushort;
typedef unsigned int uint;
typedef unsigned long ulong;
typedef unsigned long size_t;
typedef long ptrdiff_t;

#define half __clpy__half

static unsigned int atomic_cmpxchg(volatile __global unsigned int*, unsigned int, unsigned int);
static double abs(double);
static float abs(float);
static int abs(int);
static long abs(long);
static long long abs(long long);
static double acos(double);
static float acos(float);
static double acosh(double);
static float acosh(float);
static double asin(double);
static float asin(float);
static double asinh(double);
static float asinh(float);
static double atan2(double, double);
static float atan2(float, float);
static double atan(double);
static float atan(float);
static double atanh(double);
static float atanh(float);
static double cbrt(double);
static float cbrt(float);
static double ceil(double);
static float ceil(float);
static double copysign(double, double);
static float copysign(float, float);
static double cos(double);
static float cos(float);
static double cosh(double);
static float cosh(float);
static double erfc(double);
static float erfc(float);
static double erf(double);
static float erf(float);
static double exp2(double);
static float exp2(float);
static double exp(double);
static float exp(float);
static double expm1(double);
static float expm1(float);
static double fabs(double);
static float fabs(float);
static double fdim(double, double);
static float fdim(float, float);
static double floor(double);
static float floor(float);
static double fma(double, double, double);
static float fma(float, float, float);
static double fmax(double, double);
static float fmax(float, float);
static double fmin(double, double);
static float fmin(float, float);
static double fmod(double, double);
static float fmod(float, float);
static int fpclassify(double);
static int fpclassify(float);
static double frexp(double, int *);
static float frexp(float, int *);
static double hypot(double, double);
static float hypot(float, float);
static int ilogb(double);
static int ilogb(float);
static bool isfinite(double);
static bool isfinite(float);
static bool isgreater(double, double);
static bool isgreaterequal(double, double);
static bool isgreaterequal(float, float);
static bool isgreater(float, float);
static bool isinf(double);
static bool isinf(float);
static bool isless(double, double);
static bool islessequal(double, double);
static bool islessequal(float, float);
static bool isless(float, float);
static bool islessgreater(double, double);
static bool islessgreater(float, float);
static bool isnan(double);
static bool isnan(float);
static bool isnormal(double);
static bool isnormal(float);
static bool isunordered(double, double);
static bool isunordered(float, float);
static long labs(long);
static double ldexp(double, int);
static float ldexp(float, int);
static double lgamma(double);
static float lgamma(float);
static long long llabs(long long);
static long long llrint(double);
static long long llrint(float);
static double log10(double);
static float log10(float);
static double log1p(double);
static float log1p(float);
static double log2(double);
static float log2(float);
static double logb(double);
static float logb(float);
static double log(double);
static float log(float);
static long lrint(double);
static long lrint(float);
static long lround(double);
static long lround(float);
static long long llround(float);
static double modf(double, double *);
static float modf(float, float *);
static float max(float, float);
static double min(double, double);
static float max(float, float);
static double min(double, double);
static double nan(const char *);
static float nanf(const char *);
static double nearbyint(double);
static float nearbyint(float);
static double nextafter(double, double);
static float nextafter(float, float);
static double nexttoward(double, double);
static float nexttoward(float, double);
static float nexttowardf(float, double);
static double pow(double, double);
static double pow(double, int);
static float pow(float, float);
static float pow(float, int);
static double remainder(double, double);
static float remainder(float, float);
static double remquo(double, double, int *);
static float remquo(float, float, int *);
static double rint(double);
static float rint(float);
static double round(double);
static float round(float);
static double scalbln(double, long);
static float scalbln(float, long);
static double scalbn(double, int);
static float scalbn(float, int);
static bool signbit(double);
static bool signbit(float);
static double sin(double);
static float sin(float);
static double sinh(double);
static float sinh(float);
static double sqrt(double);
static float sqrt(float);
static double tan(double);
static float tan(float);
static double tanh(double);
static float tanh(float);
static double tgamma(double);
static float tgamma(float);
static double trunc(double);
static float trunc(float);
size_t get_local_id(uint);
size_t get_group_id(uint);
size_t get_global_id(uint);
size_t get_num_groups(uint);
typedef enum{
  CLK_LOCAL_MEM_FENCE,
  CLK_GLOBAL_MEM_FENCE
}cl_mem_fence_flags;
void barrier(cl_mem_fence_flags);
